config/routes.rb
Rails.application.routes.draw do
  get 'transactions/index'

  get 'transaction/index'

  get 'beneficiary/index'

  get 'beneficiaries/index'

  get 'transfers/index'

  get 'accounts/index'

  get 'admins/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #  get 'home/index'
  #  root 'home#index'
  resources :admins, only: [:index, :edit, :view] do
     get :adminsindex ,on: :collection
  end

 #get '/about' => 'home#about'
  resources :users
  #resources :transactions
#  resources :accounts
#  resources :admins

  root :to => "home#login"

  get "signup", :to => "users#signup"
  post "users", :to => "users#create"
  get "login", :to => "home#login"
  post "login_attempt", :to => "home#login_attempt"
  get "logout", :to => "home#logout"

  get "index", :to => "home#index"
  get "adminhome", :to => "home#adminhome"
  get "adminindex", :to => "admins#admin_index"
  get "userhome", :to => "home#userhome"
  get "go", :to => "home#go"

  get "accounts", :to => "accounts#index"

  # get "admins", :to => "admins#index"
  get "useraccountsrequest", :to => "home#useraccountrequest"
  get "accountsrequest", :to=> "accounts#accountrequest"
  get "accounts/create/:id", :to=> "accounts#create"
  get "accounts/delete/:id", :to=> "accounts#destroy"
  #post "accounts/:id", :to => "accounts#create"
  #delete "accounts/:id", :to => "accounts#destroy"

  get "userslist", :to => "users#userslist"
  #get "admins/:id", :to => "admins#show"

  get "transactionslist", :to => "transactions#transactionslist"
  # post '/questions' => 'home#temp'
  # post '/answers' => 'home#temp'
  #
  # get '/questions/:id' => 'home#question'

  #get "accountsrequest", :to => "home#newaccountrequest"
  get "beneficiaries", :to => "beneficiaries#index"
  get "beneficiaries/new", :to => "beneficiaries#new"
  post "beneficiaries", :to => "beneficiaries#create"

  post "transactions", :to => "transactions#create"
  post "home", :to => "home#create"

  delete "beneficiaries/:id", :to => "beneficiaries#destroy"

  get "onaccountselection", :to => "transactions#onaccountselection"


  get "transfers", :to => "transfers#index"
  get "transfers", :to => "transactions#index"
  get "usersettings", :to => "users#settings"
  get "usersprofile", :to => "users#profile"
  #get "settings", :to => "users#settings"

  post "update", :to => "users#updateprofile"

  post "updateprofile", :to => "admins#updateprofile"
  get "newadmin", :to => "admins#new"
  get "adminshowall", :to => "admins#showall"
  #get "adminsshow", :to => "admins#show"
  get "usersearch", :to => "users#usersearch"
  post "usersearch", :to => "users#usersearch"
  get "admins/:id", :to => "admins#destroy"
  get "adminaccountcreate", :to => "accounts#admincreate"
  get "accountdelete/:id", :to => "accounts#deleteaccount"
  get "userdelete/:id", :to => "users#deleteuser"

  get "admins", :to => "admins#create"
  post "admins", :to => "admins#create"

  get "transactions/:id", :to => "transactions#destroy"
  get "transactions/approve/:id", :to => "transactions#approve"
  get "transactions", :to => "transactions#index"
  get "searchuser", :to => "users#usersearch"
  post "searchuser", :to => "users#usersearch"

  # delete "admins/:id", :to => "admins#destroy"


end

app/views/admins/edit.html.erb
<% content_for :title, "Change Password" %>

<div class="col-md-2"><!--needs attention-->
  <ul class="nav nav-pills nav-stacked">
    <li class="active"><a href="/admins">Home</a></li>
    <li><a href="/transactionslist">List of Transactions</a></li>
    <li><a href="/users">Users List</a></li>
    <li><a href="/accounts">Accounts List</a></li>
    <li><a href="/accountsrequest">New Account Request</a></li>
    <li><a href="/adminshowall">Admin Details</a></li>
    <li><a href="/admins/<%=session[:admin_id]%>/edit">Edit My Profile</a></li>
    <li><a href=/logout>Log out</a></li>
  </ul>
</div>

<div class="container" style="background: #fff; margin-top: 1%; border-radius: 25px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">

  <% flash.each do |key, value| %>
      <div class="col-md-10 col-sm-12 p-a-3">
        <div class="row omb_row-sm-offset-3 no-gutter m-a-3">
          <div class="col-xs-12 col-sm-6">
            <%= content_tag(:span, value, :class => "label label-danger") %>
          </div>
        </div></div>
  <% end %>
  <% flash.clear %>
  <br/>
  <br class="row" style="padding: 20px">

  <img src="/assets/logo.png" style="padding: 5px; margin-top: 10px; margin-left: 30px; max-height: 100px; max-width: 100px"/>
  <br></br>
  <%= form_tag({:action => :updateprofile, :controller => :admins, :method => :post}, {:class => 'form-horizontal'}) %>

  <div class="form-group">
    <label for="inputName" class="col-lg-2 control-label">Name</label>
    <div class="col-lg-10">
      <%= text_field "admin", "name", "value" => @admin.name, "class" => "form-control", "placeholder" => "Full Name" %>
    </div>
  </div>
  <div class="form-group">
    <label for="inputEmail" class="col-lg-2 control-label">Email :</label>
    <div class="col-lg-10">
      <div class="col-lg-5" style="margin-top: 12px"><%=@admin.email%></div>
      <div class="col-lg-5"><%= hidden_field "admin", "email", "value" => @admin.email, "class" => "form-control" , "placeholder" => " @domain.com" %></div>
    </div>
  </div>
  <div class="form-group">
    <label for="inputPassword" class="col-lg-2 control-label">Old Password</label>
    <div class="col-lg-10">
      <%= password_field "admin", "old_password_field", "class" => "form-control" , "required" => true  %>
    </div>
  </div>
  <div class="form-group">
    <label for="inputPassword" class="col-lg-2 control-label">New Password</label>
    <div class="col-lg-10">
      <%= password_field "admin", "password_field", "class" => "form-control" %>
    </div>
  </div>
  <input type="hidden" name="admin[id]" value=<%@admin.id%>>
  <div class="form-group">
    <div class="col-lg-10 col-lg-offset-2">
      <button type="reset" class="btn btn-default">Reset</button>
      <button type="submit" class="btn btn-primary">Update</button>
    </div>
  </div>
  </form>
</div>
</div>

app/views/admins/index.html.erb
<% content_for :title, "Home" %>
<!--<h1>Admin Home Page</h1>-->

<!-- Put Navigation stuff below-->

<!-- Page content goes below-->

<div class="container" style="background: #f9f9f9; border-radius: 1px; min-height: 600px; max-width: 1200px; ">

  <div class="row">
    <div class="col-md-2"><!--needs attention-->
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><a href="/admins">Home</a></li>
        <li><a href="/transactionslist">List of Transactions</a></li>
        <li><a href="/users">Users List</a></li>
        <li><a href="/accounts">Accounts List</a></li>
        <li><a href="/accountsrequest">New Account Request</a></li>
        <li><a href="/adminshowall">Admin Details</a></li>
        <li><a href="/admins/<%=session[:admin_id]%>/edit">Edit My Profile</a></li>
        <li><a href=/logout>Log out</a></li>
      </ul>
    </div>
    <div class="col-md-10">
      <div class="row">
        <div class="col-md-4">
          <img src="/assets/logo.png" style="padding: 5px; margin-left: 30px; margin-top: 10px; max-height: 100px; max-width: 100px"/>
          <legend>My Profile</legend>
        </div>
        <div class="col-md-6">
          <div class="row">
            <div class="col-md-6 col-md-offset-3">
              
            </div>
          </div>
          <div style="margin-left: 10px; margin-top: 20px">
            <label for="select" class="control-label"></label>
            <!--TODO: Get Balance of accounts from DB and populate below-->
          </div>
        </div>

      </div>
      <label for="select" class="control-label">NEW ACCOUNT REQUESTS</label>
      <div class="jumbotron" style="background: #dfe3ee;">
        <!--TODO: Table containing a list of previous transactions come here-->
      </div>
    </div>

  </div>
</div>

app/views/admins/new.html.erb
<% content_for :title, "Add admin" %>

<!-- Navigation -->


<div class="container" style="background: #ffffff; min-height: 600px; max-width: 1200px; ">

  <div class="row">
    <div class="col-md-8">
      <img src="/assets/logo.png" style="padding: 5px; margin-top: 10px; max-height: 100px; max-width: 100px"/>
      <div class="jumbotron" style="background: #dfe3ee;">
        <legend>Add new admin account</legend>
        <%= form_tag({:controller=>"admins", :action => :create, :method => :post}, {:class => 'form-horizontal'}) %>
        <% flash.each do |key, value| %>
            <div class="row omb_row-sm-offset-3 no-gutter m-a-3">
              <div class="col-xs-12 col-sm-6">
                <%= content_tag(:span, value, :class => "label label-danger") %>
              </div>
            </div>
            <br/>
        <% end %>
        <% flash.clear %>
        <!--Name-->
        <div class="form-group">
          <label for="inputName" class="col-lg-2 control-label">Name</label>
          <div class="col-lg-10">
            <%= text_field "admin", "name", "class" => "form-control", "placeholder" => "Full Name" %>
          </div>
        </div>
        <!--Email-->
        <div class="form-group">
          <label for="inputEmail" class="col-lg-2 control-label">Email</label>
          <div class="col-lg-10">
            <%= text_field "admin", "email", "class" => "form-control" , "placeholder" => "user@domain.com"%>
            <%= hidden_field "admin", "is_pre_admin", "value" => false, "class" => "form-control" %>
          </div>
        </div>
        <!--Password-->
        <div class="form-group">
          <label for="inputPassword" class="col-lg-2 control-label">Password</label>
          <div class="col-lg-10">
            <%= password_field "admin", "password_field", "class" => "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-lg-10 col-lg-offset-2">
            <button type="reset" class="btn btn-default">Reset</button>
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /.container -->

app/views/admins/show.html.erb
<% content_for :title, "Home" %>
<!--<h1>User Home Page</h1>-->
<!-- Put Navigation stuff below-->
<!-- Page content goes below-->

<div class="container" style="background: #f9f9f9; border-radius: 1px; min-height: 600px; max-width: 1200px; ">

  <div class="row">
    <div class="col-md-2"><!--needs attention-->
      <ul class="nav nav-pills nav-stacked">
        <li><a href="/adminhome">Home</a></li>
        <li><a href="/transactionslist">List of Transactions</a></li>
        <li><a href="/userslist">Users List</a></li>
        <li><a href="/accounts">Accounts List</a></li>
        <li><a href="/accountsrequest">New Account Request</a></li>
        <li class="active"><a href="/admins/<%=session[:user_id]%>">Admin Details</a></li>
        <li><a href="/admins/<%=session[:user_id]%>/edit">Edit My Profile</a></li>
        <li><a href=/logout>Log out</a></li>
      </ul>
    </div>
    <div class="col-md-10">
      <div class="row">
        <div class="col-md-4">
          <img src="/assets/logo.png" style="padding: 5px; margin-left: 30px; margin-top: 10px; max-height: 100px; max-width: 100px"/>
          <legend>Manage admin accounts here</legend>
          <a href="/newadmin" class="btn btn-primary btn-sm">Add new admin</a>
        </div>
      </div>

      <br></br>

      <div class="row">
        <div class="col-md-8">
          <label for="select" class="control-label">List of admins</label>
          <table class="table table-striped table-hover "><thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Delete</th>
          </tr>
          </thead><tbody>
          <% @admins.each do |admin| %>
              <% if session[:user_id] != admin.id && admin.email != "admin@ncsu.edu" %>
                  <tr>
                    <td><%= admin.name %></td>
                    <td><%= admin.email %></td>
                    <% if !admin.is_pre_admin %>
                        <td>
                          <a href="<%= admin_path(@admin) %>" style="color:#222;" data-confirm="Are you sure?" data-method="destroy" rel="nofollow">
                            <i class="fa fa-trash" aria-hidden="true"></i></a>
                        </td>
                    <%else%>
                        <td></td>
                    <% end %>
                  </tr>
              <% end %>
          <% end %>
          </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admins/showall.html.erb
<% content_for :title, "Home" %>
<!--<h1>User Home Page</h1>-->
<!-- Put Navigation stuff below-->
<!-- Page content goes below-->

<div class="container" style="background: #f9f9f9; border-radius: 1px; min-height: 600px; max-width: 1200px; ">

  <div class="row">
    <div class="col-md-2"><!--needs attention-->
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><a href="/admins">Home</a></li>
        <li><a href="/transactionslist">List of Transactions</a></li>
        <li><a href="/users">Users List</a></li>
        <li><a href="/accounts">Accounts List</a></li>
        <li><a href="/accountsrequest">New Account Request</a></li>
        <li><a href="/adminshowall">Admin Details</a></li>
        <li><a href="/admins/<%=session[:admin_id]%>/edit">Edit My Profile</a></li>
        <li><a href=/logout>Log out</a></li>
      </ul>
    </div>
    <div class="col-md-10">
      <div class="row">
        <div class="col-md-4">
          <img src="/assets/logo.png" style="padding: 5px; margin-left: 30px; margin-top: 10px; max-height: 100px; max-width: 100px"/>
          <legend>Manage admin accounts here</legend>
          <a href="/newadmin" class="btn btn-primary btn-sm">Add new admin</a>
        </div>
      </div>

      <br></br>

      <div class="row">
        <div class="col-md-8">
          <label for="select" class="control-label">List of admins</label>
          <table class="table table-striped table-hover "><thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Delete</th>
          </tr>
          </thead><tbody>
          <% @admins.each do |admin| %>
              <% if session[:user_id] != admin.id && admin.email != "admin@ncsu.edu" %>
                  <tr>
                    <td><%= admin.name %></td>
                    <td><%= admin.email %></td>
                    <% if !admin.is_pre_admin %>
                        <td>
                          <a href="/admins/<%= admin.id %>" style="color:#222;" data-method="delete" rel="nofollow">
                            <i class="fa fa-trash" aria-hidden="true"></i></a>
                        </td>
                    <%else%>
                        <td></td>
                    <% end %>
                  </tr>
              <% end %>
          <% end %>
          </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>