config/routes.rb
Rails.application.routes.draw do
  get 'transactions/index'

  get 'transaction/index'

  get 'beneficiary/index'

  get 'beneficiaries/index'

  get 'transfers/index'

  get 'accounts/index'

  get 'admins/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #  get 'home/index'
  #  root 'home#index'
  resources :admins, only: [:index, :edit, :view] do
     get :adminsindex ,on: :collection
  end

 #get '/about' => 'home#about'
  resources :users
  #resources :transactions
#  resources :accounts
#  resources :admins

  root :to => "home#login"

  get "signup", :to => "users#signup"
  post "users", :to => "users#create"
  get "login", :to => "home#login"
  post "login_attempt", :to => "home#login_attempt"
  get "logout", :to => "home#logout"

  get "index", :to => "home#index"
  get "adminhome", :to => "home#adminhome"
  get "adminindex", :to => "admins#admin_index"
  get "userhome", :to => "home#userhome"
  get "go", :to => "home#go"

  get "accounts", :to => "accounts#index"

  # get "admins", :to => "admins#index"
  get "useraccountsrequest", :to => "home#useraccountrequest"
  get "accountsrequest", :to=> "accounts#accountrequest"
  get "accounts/create/:id", :to=> "accounts#create"
  get "accounts/delete/:id", :to=> "accounts#destroy"
  #post "accounts/:id", :to => "accounts#create"
  #delete "accounts/:id", :to => "accounts#destroy"

  get "userslist", :to => "users#userslist"
  #get "admins/:id", :to => "admins#show"

  get "transactionslist", :to => "transactions#transactionslist"
  # post '/questions' => 'home#temp'
  # post '/answers' => 'home#temp'
  #
  # get '/questions/:id' => 'home#question'

  #get "accountsrequest", :to => "home#newaccountrequest"
  get "beneficiaries", :to => "beneficiaries#index"
  get "beneficiaries/new", :to => "beneficiaries#new"
  post "beneficiaries", :to => "beneficiaries#create"

  post "transactions", :to => "transactions#create"
  post "home", :to => "home#create"

  delete "beneficiaries/:id", :to => "beneficiaries#destroy"

  get "onaccountselection", :to => "transactions#onaccountselection"


  get "transfers", :to => "transfers#index"
  get "transfers", :to => "transactions#index"
  get "usersettings", :to => "users#settings"
  get "usersprofile", :to => "users#profile"
  #get "settings", :to => "users#settings"

  post "update", :to => "users#updateprofile"

  post "updateprofile", :to => "admins#updateprofile"
  get "newadmin", :to => "admins#new"
  get "adminshowall", :to => "admins#showall"
  #get "adminsshow", :to => "admins#show"
  get "usersearch", :to => "users#usersearch"
  post "usersearch", :to => "users#usersearch"
  get "admins/:id", :to => "admins#destroy"
  get "adminaccountcreate", :to => "accounts#admincreate"
  get "accountdelete/:id", :to => "accounts#deleteaccount"
  get "userdelete/:id", :to => "users#deleteuser"

  get "admins", :to => "admins#create"
  post "admins", :to => "admins#create"

  get "transactions/:id", :to => "transactions#destroy"
  get "transactions/approve/:id", :to => "transactions#approve"
  get "transactions", :to => "transactions#index"
  get "searchuser", :to => "users#usersearch"
  post "searchuser", :to => "users#usersearch"

  # delete "admins/:id", :to => "admins#destroy"


end

app/models/account.rb
class Account < ApplicationRecord
  attr_accessor :account_status
  validates :email,  :presence => true
  validates :account_number, :presence => true, :uniqueness => true
  validates_length_of :account_number, :in => 1..9, :on => :create
  validates :balance,  :presence => true

  # before_save :default_values
  #
  # def default_values
  #   if !@balance
  #     @balance = 0
  #   end
  #   if !account_status
  #     account_status = true
  #   end
  #   true
  # end

  def self.match(email="", number=0)
    #account = Account.find_by_sql(["select * from Accounts where account_number = :id ", {:id => number}])
    #email == account.email
    account = Account.find_by_account_number(number)
    if account
      email == account.email
    else
      return false
    end
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  before_action :set_member, only: [:show, :edit, :update, :destroy]

  def index
    @accounts = Account.all
    @accountcreationrequests = AccountCreationRequest.all
    #@accountcreationrequests.sort { |a,b| a.status.downcase <=> b.status.downcase }
  end

  def accountrequest
    @accountcreationrequests = AccountCreationRequest.all
    #@accountcreationrequests.sort { |a,b| a.status.downcase <=> b.status.downcase }
  	render "accountrequest"
  end

  def create
    @request = AccountCreationRequest.find(params[:id])
    email = @request.email
    @request.status = "Approved"

    @account = Account.new
    @account.balance = 0
    @account.account_status = true
    @account.email = email
    if Account.last
      @account.account_number = Account.last.account_number + 1
    else
      @account.account_number = 60000000
    end

    if @account.save && @request.save
      puts "new account created"
      puts @account.account_number
      flash[:notice]="Successfully created account"
      redirect_to :action => 'accountrequest'
    else
      flash[:notice]="Trouble creating account"
      redirect_to :action => 'accountrequest'
    end
  end


  def admincreate
    @accounts = Account.all
    if params.has_key?(:q) and params[:q].present?
      @q = params[:q].strip
      @users = (User.where('email LIKE ?', "%#{@q}"))
      if(@users.length <= 0)
        render 'index'
        return
      end
    end

    email = @users[0].email


    @account = Account.new
    @account.balance = 0
    @account.account_status = true
    @account.email = email
    if Account.last
      @account.account_number = Account.last.account_number + 1
    else
      @account.account_number = 60000000
    end

    if @account.save
      puts "new account created"
      puts @account.account_number
      flash[:notice]="Successfully created account"
      render 'index'
    else
      flash[:notice]="Trouble creating account"
      render 'index'
    end
  end

  def deleteaccount
    if !checkPendingAccounts(params[:id])
      @account = Account.find(params[:id])
      @account.destroy
    else
      flash[:notice]="Pending transactions present on account"
    end

    redirect_to :action => "index"

  end

  def delete
    @request = AccountCreationRequest.find(params[:id])
    email = @request.email
    # @request.destroy
    @request.status = "Cancelled"
    if @request.save
      flash[:notice]="Request cancelled"
      redirect_to :action => 'accountrequest'
    else
      flash[:notice]="Trouble cancelling request"
      redirect_to :action => 'accountrequest'
    end

  end

  def destroy
    @request = AccountCreationRequest.find(params[:id])
    email = @request.email
    @request.status = "Cancelled"
    if @request.save
      puts "@request.status = Cancelled ---------------- save successful"
      flash[:notice]="Request cancelled"
      redirect_to :action => 'accountrequest'
    else
      puts "@request.status = Cancelled ---------------- save unsuccessful"
      flash[:notice]="Trouble cancelling request"
      redirect_to :action => 'accountrequest'
    end

  end

  def accountsindex
    redirect_to :action => :accountsindex
  end

  def create_account
    puts "create_account create_account create_account create_account create_account create_account create_account "
    @account = Account.new
  end

  # def show
  #   puts "***********************************************************************************************"
  #   puts "show show show show show show show show show show show show show show show show show show "
  #   if session[:admin_id]
  #     @accounts = Account.find_by_sql(["select * from accounts"])
  #   else
  #     redirect_to :action => 'accountrequest'
  #     #redirect_to :action => "login", :controller => "home"
  #   end
  # end

  def checkPendingAccounts(id)
    x='SELECT "transactions"."transaction_id" FROM "transactions","accounts" WHERE "accounts"."id" = "'<<id<<'" AND ("accounts"."account_number" = "transactions"."credited_acc_number" or "accounts"."account_number" = "transactions"."debited_acc_number") AND "transactions"."transaction_status"="Pending"'
    results = ActiveRecord::Base.connection.execute(x)
    return results.length > 0
  end

private

  def set_member
    @admin = Admin.find(params[:id])
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/accountrequest.html.erb
<% content_for :title, "Home" %>
<!--<h1>User Home Page</h1>-->

<!-- Put Navigation stuff below-->

<!-- Page content goes below-->

<div class="container" style="background: #f9f9f9; border-radius: 1px; min-height: 600px; max-width: 1200px; ">

  <div class="row">
    <div class="col-md-2"><!--needs attention-->
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><a href="/admins">Home</a></li>
        <li><a href="/transactionslist">List of Transactions</a></li>
        <li><a href="/users">Users List</a></li>
        <li><a href="/accounts">Accounts List</a></li>
        <li><a href="/accountsrequest">New Account Request</a></li>
        <li><a href="/adminshowall">Admin Details</a></li>
        <li><a href="/admins/<%=session[:admin_id]%>/edit">Edit My Profile</a></li>
        <li><a href=/logout>Log out</a></li>
      </ul>
    </div>
    <div class="col-md-10">
      <div class="row">
        <div class="col-md-4">
          <img src="/assets/logo.png" style="padding: 5px; margin-left: 30px; margin-top: 10px; max-height: 100px; max-width: 100px"/>
          <legend>Approve new requests here</legend>
        </div>
      </div>

      <label for="select" class="control-label">New requests</label>
      <table class="table table-striped table-hover "><thead>
      <tr>
        <th>Requestor's Email</th>
        <th>Status</th>
        <th>Approve</th>
        <th>Cancel</th>
      </tr>
      </thead>
        <tbody>
        <% if @accountcreationrequests%>
          <% @accountcreationrequests.each do |request| %>
            <% if true %>
                <tr>
                  <td><%= request.email%></td>
                  <td><%= request.status%></td>
                  <% if request.status == "Pending"%>
                    <td><a href="/accounts/create/<%= request.id %>" style="color:#00FF00;" data-method="post" rel="nofollow"> <i class="fa fa-check" aria-hidden="true"></i></a></td>
                    <td><a href="/accounts/delete/<%= request.id %>" style="color:#FF0000;" data-method="delete" rel="nofollow"> <i class="fa fa-times" aria-hidden="true"></i></a></td>
                  <%end%>
                </tr>
            <% end %>
          <% end %>
        <% end %>
        <tr>
        </tr>
        <tr>
        </tr>
        </tbody>
      </table>
  </div>
  </div>
</div>

app/views/accounts/index.html.erb
<% content_for :title, "Accounts" %>

<!-- Put Navigation stuff below-->

<!-- Page content goes below-->
<div class="container" style="background: #f9f9f9; border-radius: 1px; min-height: 600px; max-width: 1200px; ">

  <div class="row">
    <div class="col-md-2"><!--needs attention-->
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><a href="/admins">Home</a></li>
        <li><a href="/transactionslist">List of Transactions</a></li>
        <li><a href="/users">Users List</a></li>
        <li><a href="/accounts">Accounts List</a></li>
        <li><a href="/accountsrequest">New Account Request</a></li>
        <li><a href="/adminshowall">Admin Details</a></li>
        <li><a href="/admins/<%=session[:admin_id]%>/edit">Edit My Profile</a></li>
        <li><a href=/logout>Log out</a></li>
      </ul>
    </div>
    <div class="row">
      <div class="col-md-4" style=" margin-left: 30px">
        <img src="/assets/logo.png" style="padding: 5px; margin-top: 10px; max-height: 100px; max-width: 100px"/>
        <legend>Manage the list of accounts</legend>
      </div>

      <div class="row" style="margin-top: 10px; margin-left: 20px; margin-right: 20px ">
      <div class="row">
          <div class="col-md-8">
            <table class="table table-striped table-hover "><thead>
            <tr>
              <th>Account number</th>
              <th>Account User Email</th>
              <th>Balance</th>
              <th>Status</th>
            </tr>
            </thead>
              <tbody>
                <% @accounts.each do |account| %>

                    <tr>
                      <td><%= account.account_number %></td>
                      <td><%= account.email %></td>
                      <td><%= account.balance %></td>
                      <% if account.account_status == false %>
                          <td> INACTIVE </td>
                      <% else %>
                          <td> ACTIVE </td>
                      <% end %>
                      <td><a href= "/accountdelete/<%= account.id %>" class="btn btn-primary btn-sm">Delete</a>
                      </td>
                    </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
    </div>
    </div>
  </div>
  <%= form_tag(adminaccountcreate_path, method: :get, id: 'search-form') do %>
      <div class="col-md-8">
        <%= search_field_tag :q, @q, placeholder: 'Enter user\'s email', class: 'form-control col-md-8' %>
      </div>
      <div class="col-md-2">
        <%= submit_tag 'Add Account', name: nil, class: 'btn btn-primary' %>
      </div>
  <% end %>
</div>

app/views/accounts/show.html.erb
<% content_for :title, "ManageAccounts" %>
<!--<h1>User Home Page</h1>-->
<!-- Put Navigation stuff below-->
<!-- Page content goes below-->

<div class="container" style="background: #f9f9f9; border-radius: 1px; min-height: 600px; max-width: 1200px; ">

  <div class="row">
    <div class="col-md-2"><!--needs attention-->

    </div>
    <div class="col-md-10">
      <div class="row">
        <div class="col-md-4">
          <img src="/assets/logo.png" style="padding: 5px; margin-left: 30px; margin-top: 10px; max-height: 100px; max-width: 100px"/>
          <legend>Manage Accounts</legend>
        </div>


      </div>
      <label for="select" class="control-label">List of accounts</label>
      <div class="jumbotron" style="background: #dfe3ee;">
        <div class="row">
          <div class="col-md-8">
            <img src="/assets/drawing.png" style="padding: 10px;"/>
            <!--<a href="createadmin" class="btn btn-primary btn-sm">Create</a>-->
            <a href="/create_admin" class="btn btn-primary btn-sm">Create</a>
            <table class="table table-striped table-hover "><thead>
            <tr>
              <th>Account User Email</th>
              <th>Account number</th>
              <th>Delete</th>
            </tr>
            </thead><tbody>
            <% @accounts.each do |account| %>
                <% if session[:user_id] != admin.id && admin.email != "admin@ncsu.edu" %>
                    <tr>
                      <td><%= account.email %></td>
                      <td><%= account.account_number %></td>
                      <td>
                        <a href="<%= account_path(@accounts) %>" style="color:#222;" data-confirm="Are you sure?" data-method="destroy" rel="nofollow">
                          <i class="fa fa-trash" aria-hidden="true"></i></a></td> <% end %>
                </tr>
            <% end %>
            <tr>
            </tr>
            <tr>
            </tr>
            </tbody>
            </table>
            <i class="icon-edit"></i>
          </div>
          <!--TODO: Table containing a list of previous transactions come here-->
        </div>
      </div>

    </div>
  </div>
</div>